{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "from common_functions import *\n",
    "from ha_agent import *\n",
    "neutron = neutron_client.Client(username=user,\n",
    "                                            password=passwd,\n",
    "                                            tenant_name=tenant,\n",
    "                                            auth_url=\"http://%s:5000/v2.0\"%controller_ip)\n",
    "cinder = cinder_client.Client(1,user,passwd,tenant,\"http://%s:5000/v2.0\"%controller_ip)\n",
    "nova = nova_client.Client(2,user,passwd,tenant,\"http://%s:5000/v2.0\"%controller_ip,connection_pool=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2016-11-18 09:28:00,276 - ha_agent - DEBUG - Inside the info_collection...!\n",
      "2016-11-18 09:28:00,277 - novaclient.client - DEBUG - New session created for: (http://30.20.0.2:5000)\n",
      "2016-11-18 09:28:00,308 - novaclient.client - DEBUG - New session created for: (http://192.168.30.51:8774)\n",
      "2016-11-18 09:28:01,059 - ha_agent - DEBUG - Inside the info_collection...!\n",
      "2016-11-18 09:28:02,422 - ha_agent - DEBUG - Information Collected\n",
      "2016-11-18 09:28:02,426 - ha_agent - DEBUG - Delete on Terminate Status Updated\n",
      "2016-11-18 09:28:02,719 - ha_agent - WARNING - Exception in deleting instance...!\n",
      "2016-11-18 09:28:02,721 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 209, in delete_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:28:07,878 - ha_agent - WARNING - Exception in deleting instance...!\n",
      "2016-11-18 09:28:07,879 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 209, in delete_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:28:13,115 - ha_agent - WARNING - Exception in deleting instance...!\n",
      "2016-11-18 09:28:13,116 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 204, in delete_instance_status\n",
      "    tmp_ins = nova.servers.get(instance_object.id)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/v2/servers.py\", line 676, in get\n",
      "    return self._get(\"/servers/%s\" % base.getid(server), \"server\")\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/base.py\", line 339, in _get\n",
      "    resp, body = self.api.client.get(url)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 452, in get\n",
      "    return self._cs_request(url, 'GET', **kwargs)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 430, in _cs_request\n",
      "    resp, body = self._time_request(url, method, **kwargs)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 403, in _time_request\n",
      "    resp, body = self.request(url, method, **kwargs)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 397, in request\n",
      "    raise exceptions.from_response(resp, body, url, method)\n",
      "NotFound: Instance 2692088d-b159-43c0-9085-3106edf73832 could not be found. (HTTP 404) (Request-ID: req-d9d57441-9834-43de-80ca-32c608399252)\n",
      "2016-11-18 09:28:13,117 - ha_agent - DEBUG - Instance Not Found hence deleted\n",
      "2016-11-18 09:28:13,118 - ha_agent - DEBUG - Old Instance deleted\n",
      "2016-11-18 09:28:14,317 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:28:14,318 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:28:19,483 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:28:19,484 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:28:24,662 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:28:24,664 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:28:29,857 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:28:29,858 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:28:35,028 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:28:35,029 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:28:40,235 - ha_agent - DEBUG - After creation:  Instance in active state\n",
      "2016-11-18 09:28:40,236 - ha_agent - DEBUG - Recreate Finished\n",
      "2016-11-18 09:28:40,238 - ha_agent - DEBUG - Inside the info_collection...!\n",
      "{u'OS-EXT-STS:task_state': None, u'addresses': {u'admin_internal_net': [{u'OS-EXT-IPS-MAC:mac_addr': u'fa:16:3e:36:35:4d', u'version': 4, u'addr': u'40.20.0.22', u'OS-EXT-IPS:type': u'fixed'}]}, u'links': [{u'href': u'http://192.168.30.51:8774/v2/0b2cf6dd12b54710aba1e92c0a6d60d0/servers/f8a6684a-072f-493a-9bd7-7e984d373668', u'rel': u'self'}, {u'href': u'http://192.168.30.51:8774/0b2cf6dd12b54710aba1e92c0a6d60d0/servers/f8a6684a-072f-493a-9bd7-7e984d373668', u'rel': u'bookmark'}], u'image': u'', u'OS-EXT-STS:vm_state': u'active', u'OS-EXT-SRV-ATTR:instance_name': u'instance-0000005b', u'OS-SRV-USG:launched_at': u'2016-11-18T09:28:35.000000', u'flavor': {u'id': u'7', u'links': [{u'href': u'http://192.168.30.51:8774/0b2cf6dd12b54710aba1e92c0a6d60d0/flavors/7', u'rel': u'bookmark'}]}, u'id': u'f8a6684a-072f-493a-9bd7-7e984d373668', u'security_groups': [{u'name': u'default'}], u'user_id': u'0f763def7b1e4d5594524412047918d8', u'OS-DCF:diskConfig': u'AUTO', u'accessIPv4': u'', u'accessIPv6': u'', u'progress': 0, u'OS-EXT-STS:power_state': 1, u'OS-EXT-AZ:availability_zone': u'nova', u'config_drive': u'', u'status': u'ACTIVE', u'updated': u'2016-11-18T09:28:37Z', u'hostId': u'2bc7d7e535cbc82c0092a4b8c3025d84c23d6a71f0246612c3135528', u'OS-EXT-SRV-ATTR:host': u'node-23.naanal.local', u'OS-SRV-USG:terminated_at': None, u'key_name': None, u'OS-EXT-SRV-ATTR:hypervisor_hostname': u'node-23.naanal.local', u'name': u'vol_based', u'created': u'2016-11-18T09:28:14Z', u'tenant_id': u'0b2cf6dd12b54710aba1e92c0a6d60d0', u'os-extended-volumes:volumes_attached': [{u'id': u'1d28f270-19fb-467f-a66a-7c8c814536d2'}], u'metadata': {u'origin': u'node-22.naanal.local', u'moved': u'0'}}\n",
      "node-23.naanal.local\n",
      "2016-11-18 09:28:41,871 - ha_agent - DEBUG - Floating IP attached Successfully\n",
      "2016-11-18 09:28:44,123 - ha_agent - DEBUG - Volume attached Successfully\n",
      "2016-11-18 09:28:44,133 - ha_agent - DEBUG - Successfull Migration.Adding to Migrated zNode\n",
      "2016-11-18 09:28:44,154 - ha_agent - DEBUG - Removing Instance from pending\n"
     ]
    }
   ],
   "source": [
    "migrate(\"2692088d-b159-43c0-9085-3106edf73832\",\"13_15_18\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2016-09-10 10:52:25,839 - ha_agent - DEBUG - Inside the info_collection...!\n"
     ]
    }
   ],
   "source": [
    " instance_object,info,ip_list,bdm,extra = info_collection(nova,'66f08848-df22-4d94-8f70-7c766bcff5b6',cinder)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "nics = get_fixed_ip(info,neutron)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[{'net-id': u'28a043bf-6806-4806-9fa4-d05062ca20be', u'v4-fixed-ip': u'40.20.0.13'}]\n"
     ]
    }
   ],
   "source": [
    "print(nics)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "tedsafa\n"
     ]
    }
   ],
   "source": [
    "if not nics:\n",
    "    print(\"tedsafa\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2016-11-18 09:30:27,068 - novaclient.client - DEBUG - New session created for: (http://30.20.0.2:5000)\n",
      "2016-11-18 09:30:27,118 - novaclient.client - DEBUG - New session created for: (http://192.168.30.51:8774)\n",
      "[<Server: vol_based>, <Server: ha_test-2>, <Server: ha_test-1>, <Server: ha_test0-4>, <Server: ha_test0-1>, <Server: ha_test-5>, <Server: ha_test-4>, <Server: ha_test-3>]\n",
      "f8a6684a-072f-493a-9bd7-7e984d373668\n",
      "2016-11-18 09:30:27,369 - ha_agent - DEBUG - Inside the info_collection...!\n",
      "2016-11-18 09:30:27,373 - novaclient.client - DEBUG - New session created for: (http://30.20.0.2:5000)\n",
      "2016-11-18 09:30:27,408 - novaclient.client - DEBUG - New session created for: (http://192.168.30.51:8774)\n",
      "2016-11-18 09:30:28,210 - ha_agent - DEBUG - Inside the info_collection...!\n",
      "2016-11-18 09:30:29,100 - ha_agent - DEBUG - Information Collected\n",
      "2016-11-18 09:30:29,104 - ha_agent - DEBUG - Delete on Terminate Status Updated\n",
      "2016-11-18 09:30:29,468 - ha_agent - WARNING - Exception in deleting instance...!\n",
      "2016-11-18 09:30:29,469 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 209, in delete_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:30:34,588 - ha_agent - WARNING - Exception in deleting instance...!\n",
      "2016-11-18 09:30:34,590 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 209, in delete_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:30:39,655 - ha_agent - WARNING - Exception in deleting instance...!\n",
      "2016-11-18 09:30:39,657 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 204, in delete_instance_status\n",
      "    tmp_ins = nova.servers.get(instance_object.id)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/v2/servers.py\", line 676, in get\n",
      "    return self._get(\"/servers/%s\" % base.getid(server), \"server\")\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/base.py\", line 339, in _get\n",
      "    resp, body = self.api.client.get(url)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 452, in get\n",
      "    return self._cs_request(url, 'GET', **kwargs)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 430, in _cs_request\n",
      "    resp, body = self._time_request(url, method, **kwargs)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 403, in _time_request\n",
      "    resp, body = self.request(url, method, **kwargs)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 397, in request\n",
      "    raise exceptions.from_response(resp, body, url, method)\n",
      "NotFound: Instance f8a6684a-072f-493a-9bd7-7e984d373668 could not be found. (HTTP 404) (Request-ID: req-996b39dd-7df5-4b63-9abb-42491329d756)\n",
      "2016-11-18 09:30:39,658 - ha_agent - DEBUG - Instance Not Found hence deleted\n",
      "2016-11-18 09:30:39,659 - ha_agent - DEBUG - Old Instance deleted\n",
      "2016-11-18 09:30:40,903 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:30:40,906 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:30:46,045 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:30:46,047 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:30:51,236 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:30:51,238 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:30:56,473 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:30:56,475 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:31:01,607 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:31:01,609 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:31:06,803 - ha_agent - DEBUG - After creation:  Instance in active state\n",
      "2016-11-18 09:31:06,805 - ha_agent - DEBUG - Recreate Finished\n",
      "2016-11-18 09:31:06,806 - ha_agent - DEBUG - Inside the info_collection...!\n",
      "{u'OS-EXT-STS:task_state': None, u'addresses': {u'admin_internal_net': [{u'OS-EXT-IPS-MAC:mac_addr': u'fa:16:3e:97:a5:78', u'version': 4, u'addr': u'40.20.0.22', u'OS-EXT-IPS:type': u'fixed'}]}, u'links': [{u'href': u'http://192.168.30.51:8774/v2/0b2cf6dd12b54710aba1e92c0a6d60d0/servers/dcd884af-b8d6-4c9a-974b-a984a0c1db7e', u'rel': u'self'}, {u'href': u'http://192.168.30.51:8774/0b2cf6dd12b54710aba1e92c0a6d60d0/servers/dcd884af-b8d6-4c9a-974b-a984a0c1db7e', u'rel': u'bookmark'}], u'image': u'', u'OS-EXT-STS:vm_state': u'active', u'OS-EXT-SRV-ATTR:instance_name': u'instance-0000005c', u'OS-SRV-USG:launched_at': u'2016-11-18T09:31:01.000000', u'flavor': {u'id': u'7', u'links': [{u'href': u'http://192.168.30.51:8774/0b2cf6dd12b54710aba1e92c0a6d60d0/flavors/7', u'rel': u'bookmark'}]}, u'id': u'dcd884af-b8d6-4c9a-974b-a984a0c1db7e', u'security_groups': [{u'name': u'default'}], u'user_id': u'0f763def7b1e4d5594524412047918d8', u'OS-DCF:diskConfig': u'AUTO', u'accessIPv4': u'', u'accessIPv6': u'', u'progress': 0, u'OS-EXT-STS:power_state': 1, u'OS-EXT-AZ:availability_zone': u'nova', u'config_drive': u'', u'status': u'ACTIVE', u'updated': u'2016-11-18T09:31:03Z', u'hostId': u'dc122c58e4e018024c7a4bec10b9eaa7a8270be5fdb33522e4c2c107', u'OS-EXT-SRV-ATTR:host': u'node-22.naanal.local', u'OS-SRV-USG:terminated_at': None, u'key_name': None, u'OS-EXT-SRV-ATTR:hypervisor_hostname': u'node-22.naanal.local', u'name': u'vol_based', u'created': u'2016-11-18T09:30:41Z', u'tenant_id': u'0b2cf6dd12b54710aba1e92c0a6d60d0', u'os-extended-volumes:volumes_attached': [{u'id': u'1d28f270-19fb-467f-a66a-7c8c814536d2'}], u'metadata': {u'origin': u'node-23.naanal.local', u'moved': u'0'}}\n",
      "node-22.naanal.local\n",
      "2016-11-18 09:31:08,210 - ha_agent - DEBUG - Floating IP attached Successfully\n",
      "2016-11-18 09:31:11,599 - ha_agent - DEBUG - Volume attached Successfully\n",
      "2016-11-18 09:31:11,610 - ha_agent - DEBUG - Successfull Migration.Adding to Migrated zNode\n",
      "2016-11-18 09:31:11,632 - ha_agent - DEBUG - Removing Instance from pending\n",
      "5040dc06-80c8-4846-b0e2-262e8a37f18f\n",
      "2016-11-18 09:31:11,635 - ha_agent - DEBUG - Inside the info_collection...!\n",
      "2016-11-18 09:31:11,636 - novaclient.client - DEBUG - New session created for: (http://30.20.0.2:5000)\n",
      "2016-11-18 09:31:11,679 - novaclient.client - DEBUG - New session created for: (http://192.168.30.51:8774)\n",
      "2016-11-18 09:31:12,234 - ha_agent - DEBUG - Inside the info_collection...!\n",
      "2016-11-18 09:31:12,942 - ha_agent - DEBUG - Information Collected\n",
      "2016-11-18 09:31:12,963 - ha_agent - DEBUG - Delete on Terminate Status Updated\n",
      "2016-11-18 09:31:13,385 - ha_agent - WARNING - Exception in deleting instance...!\n",
      "2016-11-18 09:31:13,387 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 209, in delete_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:31:18,618 - ha_agent - WARNING - Exception in deleting instance...!\n",
      "2016-11-18 09:31:18,619 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 209, in delete_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:31:23,849 - ha_agent - WARNING - Exception in deleting instance...!\n",
      "2016-11-18 09:31:23,850 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 204, in delete_instance_status\n",
      "    tmp_ins = nova.servers.get(instance_object.id)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/v2/servers.py\", line 676, in get\n",
      "    return self._get(\"/servers/%s\" % base.getid(server), \"server\")\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/base.py\", line 339, in _get\n",
      "    resp, body = self.api.client.get(url)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 452, in get\n",
      "    return self._cs_request(url, 'GET', **kwargs)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 430, in _cs_request\n",
      "    resp, body = self._time_request(url, method, **kwargs)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 403, in _time_request\n",
      "    resp, body = self.request(url, method, **kwargs)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 397, in request\n",
      "    raise exceptions.from_response(resp, body, url, method)\n",
      "NotFound: Instance 5040dc06-80c8-4846-b0e2-262e8a37f18f could not be found. (HTTP 404) (Request-ID: req-888ab355-fc2d-4c9b-ba19-4a2ea0a83891)\n",
      "2016-11-18 09:31:23,852 - ha_agent - DEBUG - Instance Not Found hence deleted\n",
      "2016-11-18 09:31:23,853 - ha_agent - DEBUG - Old Instance deleted\n",
      "2016-11-18 09:31:25,034 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:31:25,036 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:31:30,247 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:31:30,248 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:31:35,397 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:31:35,398 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:31:40,587 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:31:40,588 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:31:45,757 - ha_agent - DEBUG - After creation:  Instance in active state\n",
      "2016-11-18 09:31:45,758 - ha_agent - DEBUG - Recreate Finished\n",
      "2016-11-18 09:31:45,759 - ha_agent - DEBUG - Inside the info_collection...!\n",
      "{u'OS-EXT-STS:task_state': None, u'addresses': {u'admin_internal_net': [{u'OS-EXT-IPS-MAC:mac_addr': u'fa:16:3e:ec:a1:0b', u'version': 4, u'addr': u'40.20.0.18', u'OS-EXT-IPS:type': u'fixed'}]}, u'links': [{u'href': u'http://192.168.30.51:8774/v2/0b2cf6dd12b54710aba1e92c0a6d60d0/servers/c8ababcb-1237-4492-87e5-3e1441884ee3', u'rel': u'self'}, {u'href': u'http://192.168.30.51:8774/0b2cf6dd12b54710aba1e92c0a6d60d0/servers/c8ababcb-1237-4492-87e5-3e1441884ee3', u'rel': u'bookmark'}], u'image': {u'id': u'c59adf34-71c6-4ea6-9d63-c8959c7001ea', u'links': [{u'href': u'http://192.168.30.51:8774/0b2cf6dd12b54710aba1e92c0a6d60d0/images/c59adf34-71c6-4ea6-9d63-c8959c7001ea', u'rel': u'bookmark'}]}, u'OS-EXT-STS:vm_state': u'active', u'OS-EXT-SRV-ATTR:instance_name': u'instance-0000005d', u'OS-SRV-USG:launched_at': u'2016-11-18T09:31:39.000000', u'flavor': {u'id': u'1', u'links': [{u'href': u'http://192.168.30.51:8774/0b2cf6dd12b54710aba1e92c0a6d60d0/flavors/1', u'rel': u'bookmark'}]}, u'id': u'c8ababcb-1237-4492-87e5-3e1441884ee3', u'security_groups': [{u'name': u'default'}], u'user_id': u'0f763def7b1e4d5594524412047918d8', u'OS-DCF:diskConfig': u'AUTO', u'accessIPv4': u'', u'accessIPv6': u'', u'progress': 0, u'OS-EXT-STS:power_state': 1, u'OS-EXT-AZ:availability_zone': u'nova', u'config_drive': u'', u'status': u'ACTIVE', u'updated': u'2016-11-18T09:31:41Z', u'hostId': u'2bc7d7e535cbc82c0092a4b8c3025d84c23d6a71f0246612c3135528', u'OS-EXT-SRV-ATTR:host': u'node-23.naanal.local', u'OS-SRV-USG:terminated_at': None, u'key_name': None, u'OS-EXT-SRV-ATTR:hypervisor_hostname': u'node-23.naanal.local', u'name': u'ha_test-2', u'created': u'2016-11-18T09:31:25Z', u'tenant_id': u'0b2cf6dd12b54710aba1e92c0a6d60d0', u'os-extended-volumes:volumes_attached': [], u'metadata': {u'origin': u'node-22.naanal.local', u'moved': u'0'}}\n",
      "node-23.naanal.local\n",
      "2016-11-18 09:31:46,696 - ha_agent - DEBUG - Floating IP attached Successfully\n",
      "2016-11-18 09:31:49,127 - ha_agent - DEBUG - Volume attached Successfully\n",
      "2016-11-18 09:31:49,138 - ha_agent - DEBUG - Successfull Migration.Adding to Migrated zNode\n",
      "2016-11-18 09:31:49,153 - ha_agent - DEBUG - Removing Instance from pending\n",
      "92cb0e8a-03ca-46ff-8a84-2d8cf8017f9c\n",
      "2016-11-18 09:31:49,156 - ha_agent - DEBUG - Inside the info_collection...!\n",
      "2016-11-18 09:31:49,157 - novaclient.client - DEBUG - New session created for: (http://30.20.0.2:5000)\n",
      "2016-11-18 09:31:49,191 - novaclient.client - DEBUG - New session created for: (http://192.168.30.51:8774)\n",
      "2016-11-18 09:31:49,462 - ha_agent - DEBUG - Inside the info_collection...!\n",
      "2016-11-18 09:31:49,838 - ha_agent - DEBUG - Information Collected\n",
      "2016-11-18 09:31:49,842 - ha_agent - DEBUG - Delete on Terminate Status Updated\n",
      "2016-11-18 09:31:50,179 - ha_agent - WARNING - Exception in deleting instance...!\n",
      "2016-11-18 09:31:50,180 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 209, in delete_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:31:55,289 - ha_agent - WARNING - Exception in deleting instance...!\n",
      "2016-11-18 09:31:55,291 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 204, in delete_instance_status\n",
      "    tmp_ins = nova.servers.get(instance_object.id)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/v2/servers.py\", line 676, in get\n",
      "    return self._get(\"/servers/%s\" % base.getid(server), \"server\")\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/base.py\", line 339, in _get\n",
      "    resp, body = self.api.client.get(url)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 452, in get\n",
      "    return self._cs_request(url, 'GET', **kwargs)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 430, in _cs_request\n",
      "    resp, body = self._time_request(url, method, **kwargs)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 403, in _time_request\n",
      "    resp, body = self.request(url, method, **kwargs)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 397, in request\n",
      "    raise exceptions.from_response(resp, body, url, method)\n",
      "NotFound: Instance 92cb0e8a-03ca-46ff-8a84-2d8cf8017f9c could not be found. (HTTP 404) (Request-ID: req-a795e334-b172-4c67-aa51-fdcdd464273e)\n",
      "2016-11-18 09:31:55,293 - ha_agent - DEBUG - Instance Not Found hence deleted\n",
      "2016-11-18 09:31:55,295 - ha_agent - DEBUG - Old Instance deleted\n",
      "2016-11-18 09:31:56,539 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:31:56,540 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:32:01,837 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:32:01,838 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:32:07,008 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:32:07,010 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:32:12,160 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:32:12,161 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:32:17,381 - ha_agent - DEBUG - After creation:  Instance in active state\n",
      "2016-11-18 09:32:17,382 - ha_agent - DEBUG - Recreate Finished\n",
      "2016-11-18 09:32:17,383 - ha_agent - DEBUG - Inside the info_collection...!\n",
      "{u'OS-EXT-STS:task_state': None, u'addresses': {u'admin_internal_net': [{u'OS-EXT-IPS-MAC:mac_addr': u'fa:16:3e:4f:db:2f', u'version': 4, u'addr': u'40.20.0.17', u'OS-EXT-IPS:type': u'fixed'}]}, u'links': [{u'href': u'http://192.168.30.51:8774/v2/0b2cf6dd12b54710aba1e92c0a6d60d0/servers/831c3c9f-8bf3-4e04-b057-293499c977bf', u'rel': u'self'}, {u'href': u'http://192.168.30.51:8774/0b2cf6dd12b54710aba1e92c0a6d60d0/servers/831c3c9f-8bf3-4e04-b057-293499c977bf', u'rel': u'bookmark'}], u'image': {u'id': u'c59adf34-71c6-4ea6-9d63-c8959c7001ea', u'links': [{u'href': u'http://192.168.30.51:8774/0b2cf6dd12b54710aba1e92c0a6d60d0/images/c59adf34-71c6-4ea6-9d63-c8959c7001ea', u'rel': u'bookmark'}]}, u'OS-EXT-STS:vm_state': u'active', u'OS-EXT-SRV-ATTR:instance_name': u'instance-0000005e', u'OS-SRV-USG:launched_at': u'2016-11-18T09:32:13.000000', u'flavor': {u'id': u'1', u'links': [{u'href': u'http://192.168.30.51:8774/0b2cf6dd12b54710aba1e92c0a6d60d0/flavors/1', u'rel': u'bookmark'}]}, u'id': u'831c3c9f-8bf3-4e04-b057-293499c977bf', u'security_groups': [{u'name': u'default'}], u'user_id': u'0f763def7b1e4d5594524412047918d8', u'OS-DCF:diskConfig': u'AUTO', u'accessIPv4': u'', u'accessIPv6': u'', u'progress': 0, u'OS-EXT-STS:power_state': 1, u'OS-EXT-AZ:availability_zone': u'nova', u'config_drive': u'', u'status': u'ACTIVE', u'updated': u'2016-11-18T09:32:15Z', u'hostId': u'dc122c58e4e018024c7a4bec10b9eaa7a8270be5fdb33522e4c2c107', u'OS-EXT-SRV-ATTR:host': u'node-22.naanal.local', u'OS-SRV-USG:terminated_at': None, u'key_name': None, u'OS-EXT-SRV-ATTR:hypervisor_hostname': u'node-22.naanal.local', u'name': u'ha_test-1', u'created': u'2016-11-18T09:31:56Z', u'tenant_id': u'0b2cf6dd12b54710aba1e92c0a6d60d0', u'os-extended-volumes:volumes_attached': [], u'metadata': {u'origin': u'node-22.naanal.local', u'moved': u'0'}}\n",
      "node-22.naanal.local\n",
      "2016-11-18 09:32:17,553 - ha_agent - DEBUG - Floating IP attached Successfully\n",
      "2016-11-18 09:32:17,554 - ha_agent - DEBUG - Volume attached Successfully\n",
      "2016-11-18 09:32:17,563 - ha_agent - DEBUG - Successfull Migration.Adding to Migrated zNode\n",
      "2016-11-18 09:32:17,578 - ha_agent - DEBUG - Removing Instance from pending\n",
      "c6c38240-de30-4b7d-86ea-697c7a29457e\n",
      "2016-11-18 09:32:17,582 - ha_agent - DEBUG - Inside the info_collection...!\n",
      "2016-11-18 09:32:17,583 - novaclient.client - DEBUG - New session created for: (http://30.20.0.2:5000)\n",
      "2016-11-18 09:32:17,616 - novaclient.client - DEBUG - New session created for: (http://192.168.30.51:8774)\n",
      "2016-11-18 09:32:17,861 - ha_agent - DEBUG - Inside the info_collection...!\n",
      "2016-11-18 09:32:18,176 - ha_agent - DEBUG - Information Collected\n",
      "2016-11-18 09:32:18,180 - ha_agent - DEBUG - Delete on Terminate Status Updated\n",
      "2016-11-18 09:32:18,605 - ha_agent - WARNING - Exception in deleting instance...!\n",
      "2016-11-18 09:32:18,607 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 209, in delete_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:32:23,756 - ha_agent - WARNING - Exception in deleting instance...!\n",
      "2016-11-18 09:32:23,758 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 209, in delete_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:32:28,822 - ha_agent - WARNING - Exception in deleting instance...!\n",
      "2016-11-18 09:32:28,823 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 204, in delete_instance_status\n",
      "    tmp_ins = nova.servers.get(instance_object.id)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/v2/servers.py\", line 676, in get\n",
      "    return self._get(\"/servers/%s\" % base.getid(server), \"server\")\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/base.py\", line 339, in _get\n",
      "    resp, body = self.api.client.get(url)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 452, in get\n",
      "    return self._cs_request(url, 'GET', **kwargs)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 430, in _cs_request\n",
      "    resp, body = self._time_request(url, method, **kwargs)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 403, in _time_request\n",
      "    resp, body = self.request(url, method, **kwargs)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 397, in request\n",
      "    raise exceptions.from_response(resp, body, url, method)\n",
      "NotFound: Instance c6c38240-de30-4b7d-86ea-697c7a29457e could not be found. (HTTP 404) (Request-ID: req-4a36e0fe-c658-48bc-9a23-b462df56c029)\n",
      "2016-11-18 09:32:28,824 - ha_agent - DEBUG - Instance Not Found hence deleted\n",
      "2016-11-18 09:32:28,825 - ha_agent - DEBUG - Old Instance deleted\n",
      "2016-11-18 09:32:29,423 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:32:29,424 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:32:34,602 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:32:34,603 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:32:39,748 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:32:39,749 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:32:44,918 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:32:44,919 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:32:50,059 - ha_agent - DEBUG - After creation:  Instance in active state\n",
      "2016-11-18 09:32:50,060 - ha_agent - DEBUG - Recreate Finished\n",
      "2016-11-18 09:32:50,061 - ha_agent - DEBUG - Inside the info_collection...!\n",
      "{u'OS-EXT-STS:task_state': None, u'addresses': {u'admin_internal_net': [{u'OS-EXT-IPS-MAC:mac_addr': u'fa:16:3e:d1:22:ff', u'version': 4, u'addr': u'40.20.0.7', u'OS-EXT-IPS:type': u'fixed'}]}, u'links': [{u'href': u'http://192.168.30.51:8774/v2/0b2cf6dd12b54710aba1e92c0a6d60d0/servers/45a7eb1e-dc8f-4a8a-9d17-205628d5f491', u'rel': u'self'}, {u'href': u'http://192.168.30.51:8774/0b2cf6dd12b54710aba1e92c0a6d60d0/servers/45a7eb1e-dc8f-4a8a-9d17-205628d5f491', u'rel': u'bookmark'}], u'image': {u'id': u'c59adf34-71c6-4ea6-9d63-c8959c7001ea', u'links': [{u'href': u'http://192.168.30.51:8774/0b2cf6dd12b54710aba1e92c0a6d60d0/images/c59adf34-71c6-4ea6-9d63-c8959c7001ea', u'rel': u'bookmark'}]}, u'OS-EXT-STS:vm_state': u'active', u'OS-EXT-SRV-ATTR:instance_name': u'instance-0000005f', u'OS-SRV-USG:launched_at': u'2016-11-18T09:32:44.000000', u'flavor': {u'id': u'1', u'links': [{u'href': u'http://192.168.30.51:8774/0b2cf6dd12b54710aba1e92c0a6d60d0/flavors/1', u'rel': u'bookmark'}]}, u'id': u'45a7eb1e-dc8f-4a8a-9d17-205628d5f491', u'security_groups': [{u'name': u'default'}], u'user_id': u'0f763def7b1e4d5594524412047918d8', u'OS-DCF:diskConfig': u'AUTO', u'accessIPv4': u'', u'accessIPv6': u'', u'progress': 0, u'OS-EXT-STS:power_state': 1, u'OS-EXT-AZ:availability_zone': u'nova', u'config_drive': u'', u'status': u'ACTIVE', u'updated': u'2016-11-18T09:32:46Z', u'hostId': u'dc122c58e4e018024c7a4bec10b9eaa7a8270be5fdb33522e4c2c107', u'OS-EXT-SRV-ATTR:host': u'node-22.naanal.local', u'OS-SRV-USG:terminated_at': None, u'key_name': None, u'OS-EXT-SRV-ATTR:hypervisor_hostname': u'node-22.naanal.local', u'name': u'ha_test0-4', u'created': u'2016-11-18T09:32:29Z', u'tenant_id': u'0b2cf6dd12b54710aba1e92c0a6d60d0', u'os-extended-volumes:volumes_attached': [], u'metadata': {u'origin': u'node-23.naanal.local', u'moved': u'0'}}\n",
      "node-22.naanal.local\n",
      "2016-11-18 09:32:50,198 - ha_agent - DEBUG - Floating IP attached Successfully\n",
      "2016-11-18 09:32:50,199 - ha_agent - DEBUG - Volume attached Successfully\n",
      "2016-11-18 09:32:50,209 - ha_agent - DEBUG - Successfull Migration.Adding to Migrated zNode\n",
      "2016-11-18 09:32:50,233 - ha_agent - DEBUG - Removing Instance from pending\n",
      "f0a58c35-435c-44eb-8ef6-bcc951edbff9\n",
      "2016-11-18 09:32:50,236 - ha_agent - DEBUG - Inside the info_collection...!\n",
      "2016-11-18 09:32:50,237 - novaclient.client - DEBUG - New session created for: (http://30.20.0.2:5000)\n",
      "2016-11-18 09:32:50,271 - novaclient.client - DEBUG - New session created for: (http://192.168.30.51:8774)\n",
      "2016-11-18 09:32:50,521 - ha_agent - DEBUG - Inside the info_collection...!\n",
      "2016-11-18 09:32:50,793 - ha_agent - DEBUG - Information Collected\n",
      "2016-11-18 09:32:50,797 - ha_agent - DEBUG - Delete on Terminate Status Updated\n",
      "2016-11-18 09:32:51,157 - ha_agent - WARNING - Exception in deleting instance...!\n",
      "2016-11-18 09:32:51,158 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 209, in delete_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:32:56,238 - ha_agent - WARNING - Exception in deleting instance...!\n",
      "2016-11-18 09:32:56,239 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 204, in delete_instance_status\n",
      "    tmp_ins = nova.servers.get(instance_object.id)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/v2/servers.py\", line 676, in get\n",
      "    return self._get(\"/servers/%s\" % base.getid(server), \"server\")\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/base.py\", line 339, in _get\n",
      "    resp, body = self.api.client.get(url)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 452, in get\n",
      "    return self._cs_request(url, 'GET', **kwargs)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 430, in _cs_request\n",
      "    resp, body = self._time_request(url, method, **kwargs)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 403, in _time_request\n",
      "    resp, body = self.request(url, method, **kwargs)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 397, in request\n",
      "    raise exceptions.from_response(resp, body, url, method)\n",
      "NotFound: Instance f0a58c35-435c-44eb-8ef6-bcc951edbff9 could not be found. (HTTP 404) (Request-ID: req-93fb92a2-76a3-433a-b845-5828e2ef671e)\n",
      "2016-11-18 09:32:56,241 - ha_agent - DEBUG - Instance Not Found hence deleted\n",
      "2016-11-18 09:32:56,243 - ha_agent - DEBUG - Old Instance deleted\n",
      "2016-11-18 09:32:57,170 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:32:57,171 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:33:02,334 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:33:02,335 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:33:07,598 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:33:07,602 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:33:12,850 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:33:12,851 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:33:18,013 - ha_agent - DEBUG - After creation:  Instance in active state\n",
      "2016-11-18 09:33:18,015 - ha_agent - DEBUG - Recreate Finished\n",
      "2016-11-18 09:33:18,018 - ha_agent - DEBUG - Inside the info_collection...!\n",
      "{u'OS-EXT-STS:task_state': None, u'addresses': {u'admin_internal_net': [{u'OS-EXT-IPS-MAC:mac_addr': u'fa:16:3e:aa:98:80', u'version': 4, u'addr': u'40.20.0.5', u'OS-EXT-IPS:type': u'fixed'}]}, u'links': [{u'href': u'http://192.168.30.51:8774/v2/0b2cf6dd12b54710aba1e92c0a6d60d0/servers/b59e950f-7578-426c-9304-e4cca397335d', u'rel': u'self'}, {u'href': u'http://192.168.30.51:8774/0b2cf6dd12b54710aba1e92c0a6d60d0/servers/b59e950f-7578-426c-9304-e4cca397335d', u'rel': u'bookmark'}], u'image': {u'id': u'c59adf34-71c6-4ea6-9d63-c8959c7001ea', u'links': [{u'href': u'http://192.168.30.51:8774/0b2cf6dd12b54710aba1e92c0a6d60d0/images/c59adf34-71c6-4ea6-9d63-c8959c7001ea', u'rel': u'bookmark'}]}, u'OS-EXT-STS:vm_state': u'active', u'OS-EXT-SRV-ATTR:instance_name': u'instance-00000060', u'OS-SRV-USG:launched_at': u'2016-11-18T09:33:15.000000', u'flavor': {u'id': u'1', u'links': [{u'href': u'http://192.168.30.51:8774/0b2cf6dd12b54710aba1e92c0a6d60d0/flavors/1', u'rel': u'bookmark'}]}, u'id': u'b59e950f-7578-426c-9304-e4cca397335d', u'security_groups': [{u'name': u'default'}], u'user_id': u'0f763def7b1e4d5594524412047918d8', u'OS-DCF:diskConfig': u'AUTO', u'accessIPv4': u'', u'accessIPv6': u'', u'progress': 0, u'OS-EXT-STS:power_state': 1, u'OS-EXT-AZ:availability_zone': u'nova', u'config_drive': u'', u'status': u'ACTIVE', u'updated': u'2016-11-18T09:33:16Z', u'hostId': u'2bc7d7e535cbc82c0092a4b8c3025d84c23d6a71f0246612c3135528', u'OS-EXT-SRV-ATTR:host': u'node-23.naanal.local', u'OS-SRV-USG:terminated_at': None, u'key_name': None, u'OS-EXT-SRV-ATTR:hypervisor_hostname': u'node-23.naanal.local', u'name': u'ha_test0-1', u'created': u'2016-11-18T09:32:57Z', u'tenant_id': u'0b2cf6dd12b54710aba1e92c0a6d60d0', u'os-extended-volumes:volumes_attached': [], u'metadata': {u'origin': u'node-23.naanal.local', u'moved': u'0'}}\n",
      "node-23.naanal.local\n",
      "2016-11-18 09:33:18,185 - ha_agent - DEBUG - Floating IP attached Successfully\n",
      "2016-11-18 09:33:18,187 - ha_agent - DEBUG - Volume attached Successfully\n",
      "2016-11-18 09:33:18,197 - ha_agent - DEBUG - Successfull Migration.Adding to Migrated zNode\n",
      "2016-11-18 09:33:18,207 - ha_agent - DEBUG - Removing Instance from pending\n",
      "584154e7-2911-48c8-beca-1b89a7eb5430\n",
      "2016-11-18 09:33:18,210 - ha_agent - DEBUG - Inside the info_collection...!\n",
      "2016-11-18 09:33:18,211 - novaclient.client - DEBUG - New session created for: (http://30.20.0.2:5000)\n",
      "2016-11-18 09:33:18,260 - novaclient.client - DEBUG - New session created for: (http://192.168.30.51:8774)\n",
      "2016-11-18 09:33:18,533 - ha_agent - DEBUG - Inside the info_collection...!\n",
      "2016-11-18 09:33:18,954 - ha_agent - DEBUG - Information Collected\n",
      "2016-11-18 09:33:18,959 - ha_agent - DEBUG - Delete on Terminate Status Updated\n",
      "2016-11-18 09:33:19,378 - ha_agent - WARNING - Exception in deleting instance...!\n",
      "2016-11-18 09:33:19,379 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 209, in delete_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:33:24,564 - ha_agent - WARNING - Exception in deleting instance...!\n",
      "2016-11-18 09:33:24,565 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 209, in delete_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:33:29,637 - ha_agent - WARNING - Exception in deleting instance...!\n",
      "2016-11-18 09:33:29,638 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 204, in delete_instance_status\n",
      "    tmp_ins = nova.servers.get(instance_object.id)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/v2/servers.py\", line 676, in get\n",
      "    return self._get(\"/servers/%s\" % base.getid(server), \"server\")\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/base.py\", line 339, in _get\n",
      "    resp, body = self.api.client.get(url)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 452, in get\n",
      "    return self._cs_request(url, 'GET', **kwargs)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 430, in _cs_request\n",
      "    resp, body = self._time_request(url, method, **kwargs)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 403, in _time_request\n",
      "    resp, body = self.request(url, method, **kwargs)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 397, in request\n",
      "    raise exceptions.from_response(resp, body, url, method)\n",
      "NotFound: Instance 584154e7-2911-48c8-beca-1b89a7eb5430 could not be found. (HTTP 404) (Request-ID: req-84914d42-aff3-4fca-a443-4fb4da008d33)\n",
      "2016-11-18 09:33:29,640 - ha_agent - DEBUG - Instance Not Found hence deleted\n",
      "2016-11-18 09:33:29,641 - ha_agent - DEBUG - Old Instance deleted\n",
      "2016-11-18 09:33:30,353 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:33:30,354 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:33:35,519 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:33:35,520 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:33:40,732 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:33:40,733 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:33:45,921 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:33:45,922 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:33:51,098 - ha_agent - DEBUG - After creation:  Instance in active state\n",
      "2016-11-18 09:33:51,099 - ha_agent - DEBUG - Recreate Finished\n",
      "2016-11-18 09:33:51,101 - ha_agent - DEBUG - Inside the info_collection...!\n",
      "{u'OS-EXT-STS:task_state': None, u'addresses': {u'admin_internal_net': [{u'OS-EXT-IPS-MAC:mac_addr': u'fa:16:3e:e6:fb:2a', u'version': 4, u'addr': u'40.20.0.21', u'OS-EXT-IPS:type': u'fixed'}]}, u'links': [{u'href': u'http://192.168.30.51:8774/v2/0b2cf6dd12b54710aba1e92c0a6d60d0/servers/50a31fab-8cf4-4692-bebe-8f6c74716527', u'rel': u'self'}, {u'href': u'http://192.168.30.51:8774/0b2cf6dd12b54710aba1e92c0a6d60d0/servers/50a31fab-8cf4-4692-bebe-8f6c74716527', u'rel': u'bookmark'}], u'image': {u'id': u'c59adf34-71c6-4ea6-9d63-c8959c7001ea', u'links': [{u'href': u'http://192.168.30.51:8774/0b2cf6dd12b54710aba1e92c0a6d60d0/images/c59adf34-71c6-4ea6-9d63-c8959c7001ea', u'rel': u'bookmark'}]}, u'OS-EXT-STS:vm_state': u'active', u'OS-EXT-SRV-ATTR:instance_name': u'instance-00000061', u'OS-SRV-USG:launched_at': u'2016-11-18T09:33:45.000000', u'flavor': {u'id': u'1', u'links': [{u'href': u'http://192.168.30.51:8774/0b2cf6dd12b54710aba1e92c0a6d60d0/flavors/1', u'rel': u'bookmark'}]}, u'id': u'50a31fab-8cf4-4692-bebe-8f6c74716527', u'security_groups': [{u'name': u'default'}], u'user_id': u'0f763def7b1e4d5594524412047918d8', u'OS-DCF:diskConfig': u'AUTO', u'accessIPv4': u'', u'accessIPv6': u'', u'progress': 0, u'OS-EXT-STS:power_state': 1, u'OS-EXT-AZ:availability_zone': u'nova', u'config_drive': u'', u'status': u'ACTIVE', u'updated': u'2016-11-18T09:33:46Z', u'hostId': u'dc122c58e4e018024c7a4bec10b9eaa7a8270be5fdb33522e4c2c107', u'OS-EXT-SRV-ATTR:host': u'node-22.naanal.local', u'OS-SRV-USG:terminated_at': None, u'key_name': None, u'OS-EXT-SRV-ATTR:hypervisor_hostname': u'node-22.naanal.local', u'name': u'ha_test-5', u'created': u'2016-11-18T09:33:30Z', u'tenant_id': u'0b2cf6dd12b54710aba1e92c0a6d60d0', u'os-extended-volumes:volumes_attached': [], u'metadata': {u'origin': u'node-23.naanal.local', u'moved': u'0'}}\n",
      "node-22.naanal.local\n",
      "2016-11-18 09:33:51,305 - ha_agent - DEBUG - Floating IP attached Successfully\n",
      "2016-11-18 09:33:51,306 - ha_agent - DEBUG - Volume attached Successfully\n",
      "2016-11-18 09:33:51,316 - ha_agent - DEBUG - Successfull Migration.Adding to Migrated zNode\n",
      "2016-11-18 09:33:51,326 - ha_agent - DEBUG - Removing Instance from pending\n",
      "7018dde0-eb8b-4b4c-ad1c-71c74b711fa6\n",
      "2016-11-18 09:33:51,328 - ha_agent - DEBUG - Inside the info_collection...!\n",
      "2016-11-18 09:33:51,329 - novaclient.client - DEBUG - New session created for: (http://30.20.0.2:5000)\n",
      "2016-11-18 09:33:51,367 - novaclient.client - DEBUG - New session created for: (http://192.168.30.51:8774)\n",
      "2016-11-18 09:33:51,594 - ha_agent - DEBUG - Inside the info_collection...!\n",
      "2016-11-18 09:33:51,955 - ha_agent - DEBUG - Information Collected\n",
      "2016-11-18 09:33:51,959 - ha_agent - DEBUG - Delete on Terminate Status Updated\n",
      "2016-11-18 09:33:52,498 - ha_agent - WARNING - Exception in deleting instance...!\n",
      "2016-11-18 09:33:52,499 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 209, in delete_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:33:57,576 - ha_agent - WARNING - Exception in deleting instance...!\n",
      "2016-11-18 09:33:57,578 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 204, in delete_instance_status\n",
      "    tmp_ins = nova.servers.get(instance_object.id)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/v2/servers.py\", line 676, in get\n",
      "    return self._get(\"/servers/%s\" % base.getid(server), \"server\")\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/base.py\", line 339, in _get\n",
      "    resp, body = self.api.client.get(url)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 452, in get\n",
      "    return self._cs_request(url, 'GET', **kwargs)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 430, in _cs_request\n",
      "    resp, body = self._time_request(url, method, **kwargs)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 403, in _time_request\n",
      "    resp, body = self.request(url, method, **kwargs)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 397, in request\n",
      "    raise exceptions.from_response(resp, body, url, method)\n",
      "NotFound: Instance 7018dde0-eb8b-4b4c-ad1c-71c74b711fa6 could not be found. (HTTP 404) (Request-ID: req-ba396e5e-8fdb-4f05-9897-e432dd7f2707)\n",
      "2016-11-18 09:33:57,579 - ha_agent - DEBUG - Instance Not Found hence deleted\n",
      "2016-11-18 09:33:57,581 - ha_agent - DEBUG - Old Instance deleted\n",
      "2016-11-18 09:33:58,325 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:33:58,326 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:34:03,521 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:34:03,522 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:34:08,694 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:34:08,695 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:34:13,838 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:34:13,839 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:34:19,017 - ha_agent - DEBUG - After creation:  Instance in active state\n",
      "2016-11-18 09:34:19,018 - ha_agent - DEBUG - Recreate Finished\n",
      "2016-11-18 09:34:19,020 - ha_agent - DEBUG - Inside the info_collection...!\n",
      "{u'OS-EXT-STS:task_state': None, u'addresses': {u'admin_internal_net': [{u'OS-EXT-IPS-MAC:mac_addr': u'fa:16:3e:ce:8b:f0', u'version': 4, u'addr': u'40.20.0.19', u'OS-EXT-IPS:type': u'fixed'}]}, u'links': [{u'href': u'http://192.168.30.51:8774/v2/0b2cf6dd12b54710aba1e92c0a6d60d0/servers/635a352e-0416-4f18-9479-ad33647ad5c6', u'rel': u'self'}, {u'href': u'http://192.168.30.51:8774/0b2cf6dd12b54710aba1e92c0a6d60d0/servers/635a352e-0416-4f18-9479-ad33647ad5c6', u'rel': u'bookmark'}], u'image': {u'id': u'c59adf34-71c6-4ea6-9d63-c8959c7001ea', u'links': [{u'href': u'http://192.168.30.51:8774/0b2cf6dd12b54710aba1e92c0a6d60d0/images/c59adf34-71c6-4ea6-9d63-c8959c7001ea', u'rel': u'bookmark'}]}, u'OS-EXT-STS:vm_state': u'active', u'OS-EXT-SRV-ATTR:instance_name': u'instance-00000062', u'OS-SRV-USG:launched_at': u'2016-11-18T09:34:13.000000', u'flavor': {u'id': u'1', u'links': [{u'href': u'http://192.168.30.51:8774/0b2cf6dd12b54710aba1e92c0a6d60d0/flavors/1', u'rel': u'bookmark'}]}, u'id': u'635a352e-0416-4f18-9479-ad33647ad5c6', u'security_groups': [{u'name': u'default'}], u'user_id': u'0f763def7b1e4d5594524412047918d8', u'OS-DCF:diskConfig': u'AUTO', u'accessIPv4': u'', u'accessIPv6': u'', u'progress': 0, u'OS-EXT-STS:power_state': 1, u'OS-EXT-AZ:availability_zone': u'nova', u'config_drive': u'', u'status': u'ACTIVE', u'updated': u'2016-11-18T09:34:15Z', u'hostId': u'2bc7d7e535cbc82c0092a4b8c3025d84c23d6a71f0246612c3135528', u'OS-EXT-SRV-ATTR:host': u'node-23.naanal.local', u'OS-SRV-USG:terminated_at': None, u'key_name': None, u'OS-EXT-SRV-ATTR:hypervisor_hostname': u'node-23.naanal.local', u'name': u'ha_test-4', u'created': u'2016-11-18T09:33:58Z', u'tenant_id': u'0b2cf6dd12b54710aba1e92c0a6d60d0', u'os-extended-volumes:volumes_attached': [], u'metadata': {u'origin': u'node-22.naanal.local', u'moved': u'0'}}\n",
      "node-23.naanal.local\n",
      "2016-11-18 09:34:19,193 - ha_agent - DEBUG - Floating IP attached Successfully\n",
      "2016-11-18 09:34:19,194 - ha_agent - DEBUG - Volume attached Successfully\n",
      "2016-11-18 09:34:19,206 - ha_agent - DEBUG - Successfull Migration.Adding to Migrated zNode\n",
      "2016-11-18 09:34:19,221 - ha_agent - DEBUG - Removing Instance from pending\n",
      "2593a50a-1d6e-4241-b25f-3ce7267ef317\n",
      "2016-11-18 09:34:19,224 - ha_agent - DEBUG - Inside the info_collection...!\n",
      "2016-11-18 09:34:19,226 - novaclient.client - DEBUG - New session created for: (http://30.20.0.2:5000)\n",
      "2016-11-18 09:34:19,318 - novaclient.client - DEBUG - New session created for: (http://192.168.30.51:8774)\n",
      "2016-11-18 09:34:19,678 - ha_agent - DEBUG - Inside the info_collection...!\n",
      "2016-11-18 09:34:20,092 - ha_agent - DEBUG - Information Collected\n",
      "2016-11-18 09:34:20,098 - ha_agent - DEBUG - Delete on Terminate Status Updated\n",
      "2016-11-18 09:34:20,500 - ha_agent - WARNING - Exception in deleting instance...!\n",
      "2016-11-18 09:34:20,502 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 209, in delete_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:34:25,733 - ha_agent - WARNING - Exception in deleting instance...!\n",
      "2016-11-18 09:34:25,735 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 209, in delete_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:34:30,800 - ha_agent - WARNING - Exception in deleting instance...!\n",
      "2016-11-18 09:34:30,801 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 204, in delete_instance_status\n",
      "    tmp_ins = nova.servers.get(instance_object.id)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/v2/servers.py\", line 676, in get\n",
      "    return self._get(\"/servers/%s\" % base.getid(server), \"server\")\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/base.py\", line 339, in _get\n",
      "    resp, body = self.api.client.get(url)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 452, in get\n",
      "    return self._cs_request(url, 'GET', **kwargs)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 430, in _cs_request\n",
      "    resp, body = self._time_request(url, method, **kwargs)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 403, in _time_request\n",
      "    resp, body = self.request(url, method, **kwargs)\n",
      "  File \"/usr/lib/python2.7/dist-packages/novaclient/client.py\", line 397, in request\n",
      "    raise exceptions.from_response(resp, body, url, method)\n",
      "NotFound: Instance 2593a50a-1d6e-4241-b25f-3ce7267ef317 could not be found. (HTTP 404) (Request-ID: req-c35218b1-7011-4cc5-b91a-9c1babb7fbe9)\n",
      "2016-11-18 09:34:30,802 - ha_agent - DEBUG - Instance Not Found hence deleted\n",
      "2016-11-18 09:34:30,803 - ha_agent - DEBUG - Old Instance deleted\n",
      "2016-11-18 09:34:31,697 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:34:31,698 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:34:36,879 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:34:36,880 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:34:42,024 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:34:42,025 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:34:47,202 - ha_agent - WARNING - Exception: checking the instance status after creation...!\n",
      "2016-11-18 09:34:47,203 - ha_agent - ERROR - \n",
      "Traceback (most recent call last):\n",
      "  File \"common_functions.py\", line 273, in create_instance_status\n",
      "    raise Exception(\"poll\")\n",
      "Exception: poll\n",
      "2016-11-18 09:34:52,411 - ha_agent - DEBUG - After creation:  Instance in active state\n",
      "2016-11-18 09:34:52,412 - ha_agent - DEBUG - Recreate Finished\n",
      "2016-11-18 09:34:52,413 - ha_agent - DEBUG - Inside the info_collection...!\n",
      "{u'OS-EXT-STS:task_state': None, u'addresses': {u'admin_internal_net': [{u'OS-EXT-IPS-MAC:mac_addr': u'fa:16:3e:ae:8d:d7', u'version': 4, u'addr': u'40.20.0.20', u'OS-EXT-IPS:type': u'fixed'}]}, u'links': [{u'href': u'http://192.168.30.51:8774/v2/0b2cf6dd12b54710aba1e92c0a6d60d0/servers/6d016b95-2d2a-49bb-b7d1-fc31ca965e82', u'rel': u'self'}, {u'href': u'http://192.168.30.51:8774/0b2cf6dd12b54710aba1e92c0a6d60d0/servers/6d016b95-2d2a-49bb-b7d1-fc31ca965e82', u'rel': u'bookmark'}], u'image': {u'id': u'c59adf34-71c6-4ea6-9d63-c8959c7001ea', u'links': [{u'href': u'http://192.168.30.51:8774/0b2cf6dd12b54710aba1e92c0a6d60d0/images/c59adf34-71c6-4ea6-9d63-c8959c7001ea', u'rel': u'bookmark'}]}, u'OS-EXT-STS:vm_state': u'active', u'OS-EXT-SRV-ATTR:instance_name': u'instance-00000063', u'OS-SRV-USG:launched_at': u'2016-11-18T09:34:48.000000', u'flavor': {u'id': u'1', u'links': [{u'href': u'http://192.168.30.51:8774/0b2cf6dd12b54710aba1e92c0a6d60d0/flavors/1', u'rel': u'bookmark'}]}, u'id': u'6d016b95-2d2a-49bb-b7d1-fc31ca965e82', u'security_groups': [{u'name': u'default'}], u'user_id': u'0f763def7b1e4d5594524412047918d8', u'OS-DCF:diskConfig': u'AUTO', u'accessIPv4': u'', u'accessIPv6': u'', u'progress': 0, u'OS-EXT-STS:power_state': 1, u'OS-EXT-AZ:availability_zone': u'nova', u'config_drive': u'', u'status': u'ACTIVE', u'updated': u'2016-11-18T09:34:49Z', u'hostId': u'2bc7d7e535cbc82c0092a4b8c3025d84c23d6a71f0246612c3135528', u'OS-EXT-SRV-ATTR:host': u'node-23.naanal.local', u'OS-SRV-USG:terminated_at': None, u'key_name': None, u'OS-EXT-SRV-ATTR:hypervisor_hostname': u'node-23.naanal.local', u'name': u'ha_test-3', u'created': u'2016-11-18T09:34:32Z', u'tenant_id': u'0b2cf6dd12b54710aba1e92c0a6d60d0', u'os-extended-volumes:volumes_attached': [], u'metadata': {u'origin': u'node-23.naanal.local', u'moved': u'0'}}\n",
      "node-23.naanal.local\n",
      "2016-11-18 09:34:52,553 - ha_agent - DEBUG - Floating IP attached Successfully\n",
      "2016-11-18 09:34:52,554 - ha_agent - DEBUG - Volume attached Successfully\n",
      "2016-11-18 09:34:52,564 - ha_agent - DEBUG - Successfull Migration.Adding to Migrated zNode\n",
      "2016-11-18 09:34:52,574 - ha_agent - DEBUG - Removing Instance from pending\n"
     ]
    }
   ],
   "source": [
    "server=nova.servers.list()\n",
    "print(server)\n",
    "for instance in server:\n",
    "    print(instance.id)    \n",
    "    migrate(instance.id,\"13_11_2016\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'instance_name': 'instance_name', 'host_name': 'tmp_hosdgdst'}\n",
      "{'instance_name': 'jhdsfads', 'old_instance_name': '123456', 'host_name': 'tmp_hosdgdst'}\n"
     ]
    }
   ],
   "source": [
    "data={\"instance_name\":\"instance_name\",\"host_name\":\"tmp_host\"}   \n",
    "data1={\"instance_name\":\"instance_name\",\"host_name\":\"tmp_hosdgdst\"}   \n",
    "data.update(data1)\n",
    "print(data)\n",
    "data[\"instance_name\"]=\"jhdsfads\"\n",
    "data[\"old_instance_name\"]=\"123456\"\n",
    "print(data)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "17_11_2016_11_8\n"
     ]
    }
   ],
   "source": [
    "date=str(host_down_time.tm_mday)+\"_\"+str(host_down_time.tm_mon)+\"_\"+str(host_down_time.tm_year)+\"_\"+str(host_down_time.tm_hour)\\\n",
    "+\"_\"+str(host_down_time.tm_min)\n",
    "print(date)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "5c2b43d3-b978-4a27-bc04-945fc7d731e7\n",
      "88853bd2-09e8-48f9-8868-37bef60c721f\n",
      "265a04ea-3f88-42b0-a7ca-b3c4d90726c8\n",
      "1fb596ca-9f42-4210-a9ad-b4d86b1435bd\n",
      "108632ae-a79f-4f04-9a0f-f6a4cf97585f\n",
      "bc48ceb2-a14a-421a-99db-1d4d7ef1f4aa\n",
      "9fdacaec-a7a2-4759-9270-4ca5c20dc690\n",
      "4c72904c-4dcc-461f-a406-f17a2082b81a\n",
      "a491a39c-6a7a-40c2-aef9-28cfe58bc22c\n",
      "040697c7-b8ad-4add-9456-aa8339126e66\n",
      "ee569c28-1b25-401e-ba65-62b2eb144639\n",
      "b926d749-469b-468a-820e-b42c74f45f1b\n",
      "c133f687-e391-4e49-8eaf-2f5aa2a61b63\n",
      "19b87149-f647-4294-9dcd-1edebb914b73\n",
      "2a74ca43-3ec2-4f0b-824b-a1b56bdcca36\n"
     ]
    }
   ],
   "source": [
    "import kazoo\n",
    "import json\n",
    "from kazoo.client import KazooClient\n",
    "zk = KazooClient(hosts='192.168.30.54:2181')\n",
    "zk.start()\n",
    "host_name=\"node-23.naanal.local\"\n",
    "new_instance_details=zk.get_children(\"/openstack_ha/instances/migrated/\"+host_name)\n",
    "for instance in new_instance_details:   \n",
    "    instance_details=zk.get(\"/openstack_ha/instances/migrated/\"+host_name+\"/\"+instance)[0]\n",
    "    my_decoded_str = instance_details.decode()    \n",
    "    output=json.loads(my_decoded_str)\n",
    "    print(output[\"instance_id\"])\n",
    "    #pass the instance_id to the migrate function recreate the instance\n",
    "    #remigration create instance to particular node i.e)down node\n",
    "    #so we needed to pass host_name to create an instance\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "f6da9cc1-e2b1-4775-8e3f-8324121cfa8a\n",
      "265a04ea-3f88-42b0-a7ca-b3c4d90726c8\n",
      "2a74ca43-3ec2-4f0b-824b-a1b56bdcca36\n",
      "88853bd2-09e8-48f9-8868-37bef60c721f\n",
      "ee569c28-1b25-401e-ba65-62b2eb144639\n",
      "c133f687-e391-4e49-8eaf-2f5aa2a61b63\n",
      "abde6793-4365-4b79-a053-af5b2bd93eb7\n"
     ]
    }
   ],
   "source": [
    "import json\n",
    "file_name='migration_error_instance_13_11_2016.json'\n",
    "vaild_json_file_name='useful_input.json'\n",
    "f2 = open(file_name)\n",
    "tempstr = f2.read()\n",
    "tempstr = tempstr[:-1]\n",
    "tempstr = '['+tempstr\n",
    "tempstr = tempstr + ']'\n",
    "with open(vaild_json_file_name, 'w') as perfect_file:\n",
    "    perfect_file.writelines(tempstr)\n",
    "with open(vaild_json_file_name) as json_data:      \n",
    "    instances = json.load(json_data)\n",
    "    #for read as string using below data\n",
    "    #data=json.dumps(d,sort_keys=True,indent=2)   \n",
    "    for instance in instances:\n",
    "        print (instance[''])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "string=\"shan\"\n",
    "string1=None\n",
    "if  string and string1:\n",
    "    print(\"true\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[<Server: ha_test-2>,\n",
       " <Server: ha_test-1>,\n",
       " <Server: ha_test0-4>,\n",
       " <Server: ha_test0-1>,\n",
       " <Server: ha_test-5>,\n",
       " <Server: ha_test-4>,\n",
       " <Server: ha_test-3>]"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "ls=list_instances(nova)\n",
    "ls"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "ns=recreate_instance(nova,instance_object=ls[0],neutron=neutron)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "u'node-22.naanal.local'"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "l=ns._info\n",
    "host=l['OS-EXT-SRV-ATTR:host']\n",
    "host"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 2",
   "language": "python",
   "name": "python2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 1
}
